### ISSUE TITLE
The link for installing nitrogen server on local machine is broken

### ISSUE THREAD

**Issue by smattoo** [nitrogenjs/client#29]
Under the section *Contibuting to the Project*, the link for running nitrogen server locally is broken.
 
Run a Nitrogen server<<BROKEN LINK>> locally that the tests can run against in test mode (NODE_ENV=test).

Request you to update this to correct one, am trying to run Nitrogen service locally.

Thanks

**Comment by timfpark** [comment]
Hi @smattoo - thanks for the issue and sorry for the broken links - I fixed them for you.
